# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bootstrap-addons-rails"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2013-03-15"
  s.description = "Adds nice Bootstrap addons to your Rails Twitter Bootstrap based app"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bootstrap-addons-rails.gemspec",
    "lib/bootstrap-addons-rails.rb",
    "spec/spec_helper.rb",
    "vendor/assets/colorpicker/css/colorpicker.css",
    "vendor/assets/colorpicker/img/alpha.png",
    "vendor/assets/colorpicker/img/hue.png",
    "vendor/assets/colorpicker/img/saturation.png",
    "vendor/assets/colorpicker/js/bootstrap-colorpicker.js",
    "vendor/assets/colorpicker/less/colorpicker.less",
    "vendor/assets/images/bootstrap/colorpicker/alpha.png",
    "vendor/assets/images/bootstrap/colorpicker/hue.png",
    "vendor/assets/images/bootstrap/colorpicker/saturation.png",
    "vendor/assets/images/bootstrap/image-gallery/loading.gif",
    "vendor/assets/javascripts/bootstrap/colorpicker.js",
    "vendor/assets/javascripts/bootstrap/datepicker.js",
    "vendor/assets/javascripts/bootstrap/image-gallery.js",
    "vendor/assets/javascripts/bootstrap/image-gallery.min.js",
    "vendor/assets/javascripts/bootstrap/load-image.min.js",
    "vendor/assets/less/bootstrap/colorpicker.less",
    "vendor/assets/less/bootstrap/datepicker.less",
    "vendor/assets/stylesheets/bootstrap/colorpicker.css",
    "vendor/assets/stylesheets/bootstrap/datepicker.css",
    "vendor/assets/stylesheets/bootstrap/image-gallery.css",
    "vendor/assets/stylesheets/bootstrap/image-gallery.min.css"
  ]
  s.homepage = "http://github.com/kristianmandrup/bootstrap-addons-rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Twitter Bootstrap addons: Color- and Datepicker, Image gallery, ready for use with Rails asset pipeline"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0.5"])
    else
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0.5"])
  end
end

